#!/bin/bash

#PBS -N unet
#PBS -o OUT
#PBS -j oe
#PBS -q pascalq
#PBS -l select=1:ncpus=8:ngpus=1
#PBS -l walltime=24:00:00
#PBS -m a

cd $PBS_O_WORKDIR

echo Running on host `hostname`
echo Time is `date`
echo Directory is `pwd`
echo PBS job ID is $PBS_JOBID

# Silence Keras CPU warnings
export TF_CPP_MIN_LOG_LEVEL=2

# Load modules
module load cudatoolkit
module load anaconda
module load cuda10.1/toolkit/10.1.243

# Train model
time python train.py
