#!/bin/bash

#PBS -N unet
#PBS -o OUT
#PBS -j oe
#PBS -q pascalq
#PBS -l select=1:ncpus=8:ngpus=1
#PBS -l walltime=05:00:00
#PBS -m a

cd $PBS_O_WORKDIR

echo Running on host `hostname`
echo Time is `date`
echo Directory is `pwd`
echo PBS job ID is $PBS_JOBID

module load anaconda/3
pip install -U scikit-image --user
module load cudnn/7.0
module load cudatoolkit/9.1.85
pip install tensorflow-gpu --user

python main.py
